### ISSUE TITLE
promise rejected issue

### ISSUE THREAD

**Issue by thebookins** [thebookins/xdrip-js#22]
@ericfeibelman reported the following error message:
```
noble warning: unknown peripheral ee0d6de37911
/root/src/xdrip-js/lib/bluetooth-manager.js:118
reject('received ' + data.toString('hex') + ', expecting ' + firstByte.toString('hex'));
^
RangeError: toString() radix argument must be between 2 and 36
at Number.toString (native)
at /root/src/xdrip-js/lib/bluetooth-manager.js:118:82
at Characteristic.<anonymous> (/root/src/xdrip-js/node_modules/noble/lib/characteristic.js:47:9)
at emitTwo (events.js:106:13)
at Characteristic.emit (events.js:191:7)
at Noble.onRead (/root/src/xdrip-js/node_modules/noble/lib/noble.js:283:20)
at emitMany (events.js:127:13)
at NobleBindings.emit (events.js:201:7)
at NobleBindings.onRead (/root/src/xdrip-js/node_modules/noble/lib/hci-socket/bindings.js:356:8)
at emitMany (events.js:127:13)
```

There appear to be two issues here:
1. the transmitter is encountering an unexpected opcode
2. the `toString()` method is failing, so no debug information is provided

**Comment by thebookins** [comment]
The `toString()` error should be fixed with https://github.com/thebookins/xdrip-js/commit/940521e67e4b9c51e981e5289617af6a44e1e8e0; if this point is hit in the code again we should get a more informative error message and respond accordingly.
