### ISSUE TITLE
wrong date at startup

### ISSUE THREAD

**Issue by thebookins** [thebookins/xdrip-js#46]
On startup the Edison appears to get stuck sometimes with the wrong date. It usually rights itself, but for a while there is is convinced that it has just turned midnight on 1 January 2000. If a transmission is received while in this state, it will have in incorrect read date. Additionally, if a calibration is attempted it will likely fail. Here's the log when last noticed:
```text
Dec 30 03:08:45 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:00:59 GMT bluetooth-manager on -> stateChange: poweredOn
Dec 30 03:08:45 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:00:59 GMT bluetooth-manager starting scanning
Dec 30 03:08:45 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:00:59 GMT bluetooth-manager on -> scanStart
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:35 GMT bluetooth-manager Sat Jan 01 2000 11:01:35 GMT+1100 (AEDT): peripheral: Dexcom1J with rssi -88
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:35 GMT bluetooth-manager on -> scanStop
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager on -> connect
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager on -> peripheral services discovered
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager on -> service characteristics discovered
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager Tx 01f5163c6417cd44d202
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager Rx 03d6bf7ea9d199a0b5dba0a3d29d885d43
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager Tx 047f83dbd057923540
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager Rx 050102
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT transmitter transmitter responded with status message 050102
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager Tx 0619
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager Tx 07
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager setting notify to true
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager successfully set notify enabled for f8083534849e531cc59430f1f86a4ea5 to true
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT transmitter Version info up to date, returning.
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager Tx 24e664
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager Rx 250072c76e0048826600010000002d88
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager Tx 305336
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager Rx 31009f5d00006ec76e0073000704da37
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager Tx 2eacc5
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager Rx 2f006ec76e00a02c020060200200b7bb
Dec 30 03:08:46 shihab xdrip-js.log:  got glucose: 115
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager Tx 321116
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager Rx 330035380090013800c0006e00dd066e002438
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager setting notify to false
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager successfully set notify enabled for f8083534849e531cc59430f1f86a4ea5 to false
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT transmitter No need to backfill, returning.
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:36 GMT bluetooth-manager Tx 09
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:37 GMT bluetooth-manager disconnected peripheral
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:01:37 GMT bluetooth-manager scanning again in 1 minute
Dec 30 03:08:46 shihab xdrip-js.log:  error posting json:  { Error: getaddrinfo ENOTFOUND second15.herokuapp.com second15.herokuapp.com:80
Dec 30 03:08:46 shihab xdrip-js.log:      at errnoException (dns.js:28:10)
Dec 30 03:08:46 shihab xdrip-js.log:      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
Dec 30 03:08:46 shihab xdrip-js.log:    code: 'ENOTFOUND',
Dec 30 03:08:46 shihab xdrip-js.log:    errno: 'ENOTFOUND',
Dec 30 03:08:46 shihab xdrip-js.log:    syscall: 'getaddrinfo',
Dec 30 03:08:46 shihab xdrip-js.log:    hostname: 'second15.herokuapp.com',
Dec 30 03:08:46 shihab xdrip-js.log:    host: 'second15.herokuapp.com',
Dec 30 03:08:46 shihab xdrip-js.log:    port: 80 }
Dec 30 03:08:46 shihab xdrip-js.log:  exited
Dec 30 03:08:46 shihab xdrip-js.log:  uploaded to xDripAPS, statusCode = 200
Dec 30 03:08:46 shihab xdrip-js.log:  Client connected
Dec 30 03:08:46 shihab xdrip-js.log:  about to emit id 40XY1J
Dec 30 03:08:46 shihab xdrip-js.log:  kicking off
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:02:39 GMT bluetooth-manager on -> stateChange: poweredOn
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:02:39 GMT bluetooth-manager starting scanning
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 01 Jan 2000 00:02:39 GMT bluetooth-manager on -> scanStart
Dec 30 03:08:46 shihab xdrip-js.log:  received calibration of 121
Dec 30 03:08:46 shihab xdrip-js.log:  noble warning: unknown handle 12 disconnected!
Dec 30 03:08:46 shihab xdrip-js.log:  noble warning: unknown handle 12 disconnected!
Dec 30 03:08:46 shihab xdrip-js.log:  Client disconnected
Dec 30 03:08:46 shihab xdrip-js.log:  noble warning: unknown handle 12 disconnected!
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:45 GMT bluetooth-manager Sat Dec 30 2017 22:08:45 GMT+1100 (AEDT): peripheral: Dexcom1J with rssi -87
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:45 GMT bluetooth-manager on -> scanStop
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:45 GMT bluetooth-manager on -> connect
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:46 GMT bluetooth-manager on -> peripheral services discovered
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:46 GMT bluetooth-manager on -> service characteristics discovered
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:46 GMT bluetooth-manager Tx 0149b41c1ce86c445602
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:46 GMT bluetooth-manager Rx 0384409d8937c1efd12d78ff872604ea5f
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:46 GMT bluetooth-manager Tx 04189f8ab0342aacc5
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:46 GMT bluetooth-manager Rx 050102
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:46 GMT transmitter transmitter responded with status message 050102
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:46 GMT bluetooth-manager Tx 0619
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:46 GMT bluetooth-manager Tx 07
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:46 GMT bluetooth-manager setting notify to true
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:46 GMT bluetooth-manager successfully set notify enabled for f8083534849e531cc59430f1f86a4ea5 to true
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:46 GMT transmitter Version info up to date, returning.
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:46 GMT bluetooth-manager Tx 24e664
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:46 GMT bluetooth-manager Rx 25009ec86e004882660001000000230c
Dec 30 03:08:46 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:08:46 GMT transmitter TypeError: "value" argument is out of bounds
Dec 30 03:08:46 shihab xdrip-js.log:      at checkInt (buffer.js:1041:11)
Dec 30 03:08:46 shihab xdrip-js.log:      at Buffer.writeUInt32LE (buffer.js:1121:5)
Dec 30 03:08:46 shihab xdrip-js.log:      at new CalibrateGlucoseTxMessage (/root/src/Lookout/node_modules/xdrip-js/lib/messages/calibrate-glucose-tx-message.js:8:13)
Dec 30 03:08:46 shihab xdrip-js.log:      at promise.then (/root/src/Lookout/node_modules/xdrip-js/lib/transmitter.js:244:38)
Dec 30 03:08:46 shihab xdrip-js.log:      at process._tickCallback (internal/process/next_tick.js:109:7)
Dec 30 03:09:09 shihab xdrip-js.log:  Reading file /root/myopenaps/enact/enacted.json
Dec 30 03:09:10 shihab xdrip-js.log:  { date: 1514632148748, rate: 0, duration: 0, units: undefined }
Dec 30 03:09:11 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:09:11 GMT bluetooth-manager disconnected peripheral
Dec 30 03:09:11 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:09:11 GMT bluetooth-manager scanning again in 1 minute
Dec 30 03:09:11 shihab xdrip-js.log:  exited
Dec 30 03:09:19 shihab xdrip-js.log:  Reading file myopenaps/settings/basal_profile.json
Dec 30 03:10:14 shihab xdrip-js.log:  kicking off
Dec 30 03:10:14 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:10:14 GMT bluetooth-manager on -> stateChange: poweredOn
Dec 30 03:10:14 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:10:14 GMT bluetooth-manager starting scanning
Dec 30 03:10:14 shihab xdrip-js.log:  Sat, 30 Dec 2017 11:10:14 GMT bluetooth-manager on -> scanStart
Dec 30 03:18:56 shihab xdrip-js.log: Listening on 3000
Dec 30 03:18:56 shihab xdrip-js.log: Reading file /root/myopenaps/enact/enacted.json
Dec 30 03:18:56 shihab xdrip-js.log: Reading file myopenaps/settings/basal_profile.json
Dec 30 03:18:56 shihab xdrip-js.log: Client connected
Dec 30 03:18:56 shihab xdrip-js.log: { date: 1514632148748, rate: 0, duration: 0, units: undefined }
Dec 30 03:18:56 shihab xdrip-js.log: kicking off
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:23 GMT bluetooth-manager on -> stateChange: poweredOn
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:23 GMT bluetooth-manager starting scanning
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:23 GMT bluetooth-manager on -> scanStart
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:45 GMT bluetooth-manager Sat Dec 30 2017 22:18:45 GMT+1100 (AEDT): peripheral: Dexcom1J with rssi -91
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:45 GMT bluetooth-manager on -> scanStop
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:45 GMT bluetooth-manager on -> connect
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:46 GMT bluetooth-manager on -> peripheral services discovered
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:46 GMT bluetooth-manager on -> service characteristics discovered
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:46 GMT bluetooth-manager Tx 015365663ebe8b4e8502
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:46 GMT bluetooth-manager Rx 0373f4751b8c930b6436e93bff17ad5b43
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:46 GMT bluetooth-manager Tx 040386fe8065b91dfb
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:46 GMT bluetooth-manager Rx 050102
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:46 GMT transmitter transmitter responded with status message 050102
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:46 GMT bluetooth-manager Tx 0619
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:46 GMT bluetooth-manager Tx 07
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:46 GMT bluetooth-manager setting notify to true
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:46 GMT bluetooth-manager successfully set notify enabled for f8083534849e531cc59430f1f86a4ea5 to true
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:46 GMT transmitter Version info up to date, returning.
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:46 GMT bluetooth-manager Tx 24e664
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:47 GMT bluetooth-manager Rx 2500f6ca6e004882660001000000d804
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:47 GMT bluetooth-manager Tx 305336
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:47 GMT bluetooth-manager Rx 3100a25d0000f2ca6e007f00070815ce
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:47 GMT bluetooth-manager Tx 2eacc5
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:47 GMT bluetooth-manager Rx 2f00f2ca6e0000530200c0410200f6d5
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:47 GMT bluetooth-manager Tx 321116
Dec 30 03:18:56 shihab xdrip-js.log: got glucose: 127
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:47 GMT bluetooth-manager Rx 3300353d0090013d00cf006e00dd066e0052a5
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:47 GMT bluetooth-manager setting notify to false
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:47 GMT bluetooth-manager successfully set notify enabled for f8083534849e531cc59430f1f86a4ea5 to false
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:47 GMT transmitter No need to backfill, returning.
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:47 GMT bluetooth-manager Tx 09
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:47 GMT bluetooth-manager disconnected peripheral
Dec 30 03:18:56 shihab xdrip-js.log: Sat, 30 Dec 2017 11:18:47 GMT bluetooth-manager scanning again in 1 minute
Dec 30 03:18:56 shihab xdrip-js.log: exited
Dec 30 03:18:56 shihab xdrip-js.log: uploaded to xDripAPS, statusCode = 200
Dec 30 03:18:56 shihab xdrip-js.log: uploaded to NS, statusCode = 200
Dec 30 03:19:50 shihab xdrip-js.log: kicking off
Dec 30 03:19:50 shihab xdrip-js.log: Sat, 30 Dec 2017 11:19:50 GMT bluetooth-manager on -> stateChange: poweredOn
Dec 30 03:19:50 shihab xdrip-js.log: Sat, 30 Dec 2017 11:19:50 GMT bluetooth-manager starting scanning
Dec 30 03:19:50 shihab xdrip-js.log: Sat, 30 Dec 2017 11:19:50 GMT bluetooth-manager on -> scanStart
Dec 30 03:20:05 shihab xdrip-js.log: Client disconnected
Dec 30 03:20:06 shihab xdrip-js.log: Client connected
Dec 30 03:20:06 shihab xdrip-js.log: about to emit id 40XY1J
Dec 30 03:20:34 shihab xdrip-js.log: Reading file /root/myopenaps/enact/enacted.json
Dec 30 03:20:35 shihab xdrip-js.log: { date: 1514632833781,
Dec 30 03:20:35 shihab xdrip-js.log:   rate: 1.15,
Dec 30 03:20:35 shihab xdrip-js.log:   duration: 30,
Dec 30 03:20:35 shihab xdrip-js.log:   units: undefined }
Dec 30 03:20:42 shihab xdrip-js.log: Reading file myopenaps/settings/basal_profile.json
```

**Comment by jpcunningh** [comment]
@thebookins, do you think a simple hard coded test if the rig's date is after 01/01/2010 (nice, round date picked at random) would solve this?

We could handle the date check in Lookout / Logger to prevent xdrip-js from getting called while in a bad state.
